#!/usr/bin/env bash

function set_bash_error_handling() {
    set -euo pipefail
}

function go_to_project_root_directory() {
    local -r script_dir=$( dirname "${BASH_SOURCE[0]}")

    cd "$script_dir/.."
}

function generate_documentation_snippets() {
    ginkgo -p -r integration_test/
}

function main() {
    set_bash_error_handling
    go_to_project_root_directory

    generate_documentation_snippets
}


main
